name: flutter_library
description: A new Flutter library.
version: 0.0.1
homepage: https://github.com/MrTangBo/flutter_library

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.0
  flutter_easyrefresh: 2.2.1
  flutter_swiper: 1.1.6
  get: ^4.3.0
  shared_preferences: ^2.0.6
  connectivity_plus: ^1.0.6
  flutter_easyloading: ^3.0.0
  fluttertoast: ^8.0.8
  date_format: ^2.0.2
#  flutter_datetime_picker: ^1.5.1
  octo_image: ^1.0.0+1
  image_picker: ^0.8.3
  fijkplayer: ^0.10.0
  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


